test_dataset:
  dataset:
    name: paired-image-folders
    args:
      #root_path_1: ./data/IXI/IXI_HR/PD/test
      #root_path_2: ./data/IXI/IXI_LR/bicubic_3x/PD/test
      root_path_1: ./data/benchmark/Set14/hr
      root_path_2: ./data/benchmark/Set14/image_SRF_2
  batch_size: 1
#eval_type: benchmark-2
#eval_bsize: 300


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}