test_dataset:
  dataset:
    name: image-folder-ixi
    args:
      root_path: ./data/IXI/IXI_HR/T1/test
  wrapper:
      name: sr-implicit-downsampled-fast-ixi
      args: 
        scale_min: 8
        scale_max: 8
  batch_size: 1
eval_type: ixi-8
eval_bsize: 32


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}