test_dataset:
  dataset:
    name: image-folder-ixi
    args:
      root_path: ./data/IXI/IXI_HR/T1/test
      #root_path_1: ./data/IXI/IXI_LR/bicubic_2x/PD/test
      #root_path_2: ./data/IXI/IXI_HR/PD/test
  wrapper:
      name: sr-implicit-downsampled-fast
      args: 
        scale_min: 4
  batch_size: 1
eval_type: ixi-4
#eval_bsize: 300


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}