test_dataset:
  dataset:
    name: paired-image-folders-depth
    args:
      #root_path: ./data/DIV2K_valid_HR
      root_path: ./data/mid/x4
      #root_path: ./data/lu/x16
  batch_size: 1
eval_type: Middlebury-4
#eval_type: Lu-4
#Middlebury-16
#eval_bsize: 300


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: srno
  args:
    encoder_spec:
      name: rdn
      args:
        no_upsampling: true
    width: 256
    out_dim: 3
