train_dataset:
  dataset:
    name: image-folder-hcp
    args:
      root_path: ./HCP_SRNO/data/splited_data/train
      repeat: 1
  wrapper:
    name: sr-implicit-downsampled-fast-hcp
    args:
      inp_size: 48
      scale_max: 4
      augment: true
  batch_size: 24

val_dataset:
  dataset:
    name: image-folder-hcp
    args:
      root_path: ./HCP_SRNO/data/splited_data/val
  wrapper:
      name: sr-implicit-downsampled-fast-hcp
      args:
        scale_min: 2
        scale_max: 2
  batch_size: 1
#eval_type: div2k-2
#eval_bsize: 500


data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: sronet
  args:
    encoder_spec:
      name: rdn-3d
      #name: simple
      args:
        # no_upsampling: true
        # n_colors: 1
        feature_dim : 64
        #width: 64
    width: 512
    blocks: 16
    out_dim: 1

optimizer:
  name: adam
  args:
    lr: 1.e-5
    #lr: 8.e-5
    #weight_decay: 1.e-5
epoch_max: 2050
warmup_step_lr:
  multiplier: 10
  total_epoch: 50
#multi_step_lr:
#  milestones: [200, 400, 600, 800, 1000]
#  gamma: 0.5

epoch_val: 50
epoch_save: 25

#resume: ./save/edsr_batch_128/epoch-last.pth
